# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T01:06:09+00:00

from __future__ import annotations

from datetime import date as date_aliased
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, RootModel


class Scope(BaseModel):
    type: Optional[str] = Field(
        None,
        description='The type of the scope. Possible values are:  \n- "default" - The public scope. This is the default value. \n- "user" - Limits the scope to a single user. \n- "group" - Limits the scope to a group. \n- "domain" - Limits the scope to a domain.  Note: The permissions granted to the "default", or public, scope apply to any user, authenticated or not.',
    )
    value: Optional[str] = Field(
        None,
        description='The email address of a user or group, or the name of a domain, depending on the scope type. Omitted for type "default".',
    )


class AclRule(BaseModel):
    etag: Optional[str] = Field(None, description='ETag of the resource.')
    id: Optional[str] = Field(
        None,
        description='Identifier of the Access Control List (ACL) rule. See Sharing calendars.',
    )
    kind: Optional[str] = Field(
        'calendar#aclRule', description='Type of the resource ("calendar#aclRule").'
    )
    role: Optional[str] = Field(
        None,
        description='The role assigned to the scope. Possible values are:  \n- "none" - Provides no access. \n- "freeBusyReader" - Provides read access to free/busy information. \n- "reader" - Provides read access to the calendar. Private events will appear to users with reader access, but event details will be hidden. \n- "writer" - Provides read and write access to the calendar. Private events will appear to users with writer access, and event details will be visible. \n- "owner" - Provides ownership of the calendar. This role has all of the permissions of the writer role with the additional ability to see and manipulate ACLs.',
    )
    scope: Optional[Scope] = Field(
        None,
        description='The extent to which calendar access is granted by this ACL rule.',
    )


class CalendarNotification(BaseModel):
    method: Optional[str] = Field(
        None,
        description='The method used to deliver the notification. The possible value is:  \n- "email" - Notifications are sent via email.  \nRequired when adding a notification.',
    )
    type: Optional[str] = Field(
        None,
        description='The type of notification. Possible values are:  \n- "eventCreation" - Notification sent when a new event is put on the calendar. \n- "eventChange" - Notification sent when an event is changed. \n- "eventCancellation" - Notification sent when an event is cancelled. \n- "eventResponse" - Notification sent when an attendee responds to the event invitation. \n- "agenda" - An agenda with the events of the day (sent out in the morning).  \nRequired when adding a notification.',
    )


class Channel(BaseModel):
    address: Optional[str] = Field(
        None,
        description='The address where notifications are delivered for this channel.',
    )
    expiration: Optional[str] = Field(
        None,
        description='Date and time of notification channel expiration, expressed as a Unix timestamp, in milliseconds. Optional.',
    )
    id: Optional[str] = Field(
        None,
        description='A UUID or similar unique string that identifies this channel.',
    )
    kind: Optional[str] = Field(
        'api#channel',
        description='Identifies this as a notification channel used to watch for changes to a resource, which is "api#channel".',
    )
    params: Optional[Dict[str, str]] = Field(
        None,
        description='Additional parameters controlling delivery channel behavior. Optional.',
    )
    payload: Optional[bool] = Field(
        None,
        description='A Boolean value to indicate whether payload is wanted. Optional.',
    )
    resourceId: Optional[str] = Field(
        None,
        description='An opaque ID that identifies the resource being watched on this channel. Stable across different API versions.',
    )
    resourceUri: Optional[str] = Field(
        None, description='A version-specific identifier for the watched resource.'
    )
    token: Optional[str] = Field(
        None,
        description='An arbitrary string delivered to the target address with each notification delivered over this channel. Optional.',
    )
    type: Optional[str] = Field(
        None,
        description='The type of delivery mechanism used for this channel. Valid values are "web_hook" (or "webhook"). Both values refer to a channel where Http requests are used to deliver messages.',
    )


class ColorDefinition(BaseModel):
    background: Optional[str] = Field(
        None, description='The background color associated with this color definition.'
    )
    foreground: Optional[str] = Field(
        None,
        description="The foreground color that can be used to write on top of a background with 'background' color.",
    )


class Colors(BaseModel):
    calendar: Optional[Dict[str, ColorDefinition]] = Field(
        None,
        description='A global palette of calendar colors, mapping from the color ID to its definition. A calendarListEntry resource refers to one of these color IDs in its colorId field. Read-only.',
    )
    event: Optional[Dict[str, ColorDefinition]] = Field(
        None,
        description='A global palette of event colors, mapping from the color ID to its definition. An event resource may refer to one of these color IDs in its colorId field. Read-only.',
    )
    kind: Optional[str] = Field(
        'calendar#colors', description='Type of the resource ("calendar#colors").'
    )
    updated: Optional[datetime] = Field(
        None,
        description='Last modification time of the color palette (as a RFC3339 timestamp). Read-only.',
    )


class ConferenceParametersAddOnParameters(BaseModel):
    parameters: Optional[Dict[str, str]] = None


class ConferenceProperties(BaseModel):
    allowedConferenceSolutionTypes: Optional[List[str]] = Field(
        None,
        description='The types of conference solutions that are supported for this calendar.\nThe possible values are:  \n- "eventHangout" \n- "eventNamedHangout" \n- "hangoutsMeet"  Optional.',
    )


class ConferenceRequestStatus(BaseModel):
    statusCode: Optional[str] = Field(
        None,
        description='The current status of the conference create request. Read-only.\nThe possible values are:  \n- "pending": the conference create request is still being processed.\n- "success": the conference create request succeeded, the entry points are populated.\n- "failure": the conference create request failed, there are no entry points.',
    )


class ConferenceSolutionKey(BaseModel):
    type: Optional[str] = Field(
        None,
        description='The conference solution type.\nIf a client encounters an unfamiliar or empty type, it should still be able to display the entry points. However, it should disallow modifications.\nThe possible values are:  \n- "eventHangout" for Hangouts for consumers (deprecated; existing events may show this conference solution type but new conferences cannot be created)\n- "eventNamedHangout" for classic Hangouts for Google Workspace users (deprecated; existing events may show this conference solution type but new conferences cannot be created)\n- "hangoutsMeet" for Google Meet (http://meet.google.com)\n- "addOn" for 3P conference providers',
    )


class CreateConferenceRequest(BaseModel):
    conferenceSolutionKey: Optional[ConferenceSolutionKey] = Field(
        None, description='The conference solution, such as Hangouts or Google Meet.'
    )
    requestId: Optional[str] = Field(
        None,
        description='The client-generated unique ID for this request.\nClients should regenerate this ID for every new request. If an ID provided is the same as for the previous request, the request is ignored.',
    )
    status: Optional[ConferenceRequestStatus] = Field(
        None, description='The status of the conference create request.'
    )


class EntryPoint(BaseModel):
    accessCode: Optional[str] = Field(
        None,
        description='The access code to access the conference. The maximum length is 128 characters.\nWhen creating new conference data, populate only the subset of {meetingCode, accessCode, passcode, password, pin} fields that match the terminology that the conference provider uses. Only the populated fields should be displayed.\nOptional.',
    )
    entryPointFeatures: Optional[List[str]] = Field(
        None,
        description='Features of the entry point, such as being toll or toll-free. One entry point can have multiple features. However, toll and toll-free cannot be both set on the same entry point.',
    )
    entryPointType: Optional[str] = Field(
        None,
        description='The type of the conference entry point.\nPossible values are:  \n- "video" - joining a conference over HTTP. A conference can have zero or one video entry point.\n- "phone" - joining a conference by dialing a phone number. A conference can have zero or more phone entry points.\n- "sip" - joining a conference over SIP. A conference can have zero or one sip entry point.\n- "more" - further conference joining instructions, for example additional phone numbers. A conference can have zero or one more entry point. A conference with only a more entry point is not a valid conference.',
    )
    label: Optional[str] = Field(
        None,
        description='The label for the URI. Visible to end users. Not localized. The maximum length is 512 characters.\nExamples:  \n- for video: meet.google.com/aaa-bbbb-ccc\n- for phone: +1 123 268 2601\n- for sip: 12345678@altostrat.com\n- for more: should not be filled  \nOptional.',
    )
    meetingCode: Optional[str] = Field(
        None,
        description='The meeting code to access the conference. The maximum length is 128 characters.\nWhen creating new conference data, populate only the subset of {meetingCode, accessCode, passcode, password, pin} fields that match the terminology that the conference provider uses. Only the populated fields should be displayed.\nOptional.',
    )
    passcode: Optional[str] = Field(
        None,
        description='The passcode to access the conference. The maximum length is 128 characters.\nWhen creating new conference data, populate only the subset of {meetingCode, accessCode, passcode, password, pin} fields that match the terminology that the conference provider uses. Only the populated fields should be displayed.',
    )
    password: Optional[str] = Field(
        None,
        description='The password to access the conference. The maximum length is 128 characters.\nWhen creating new conference data, populate only the subset of {meetingCode, accessCode, passcode, password, pin} fields that match the terminology that the conference provider uses. Only the populated fields should be displayed.\nOptional.',
    )
    pin: Optional[str] = Field(
        None,
        description='The PIN to access the conference. The maximum length is 128 characters.\nWhen creating new conference data, populate only the subset of {meetingCode, accessCode, passcode, password, pin} fields that match the terminology that the conference provider uses. Only the populated fields should be displayed.\nOptional.',
    )
    regionCode: Optional[str] = Field(
        None,
        description='The CLDR/ISO 3166 region code for the country associated with this phone access. Example: "SE" for Sweden.\nCalendar backend will populate this field only for EntryPointType.PHONE.',
    )
    uri: Optional[str] = Field(
        None,
        description='The URI of the entry point. The maximum length is 1300 characters.\nFormat:  \n- for video, http: or https: schema is required.\n- for phone, tel: schema is required. The URI should include the entire dial sequence (e.g., tel:+12345678900,,,123456789;1234).\n- for sip, sip: schema is required, e.g., sip:12345678@myprovider.com.\n- for more, http: or https: schema is required.',
    )


class Error(BaseModel):
    domain: Optional[str] = Field(
        None, description='Domain, or broad category, of the error.'
    )
    reason: Optional[str] = Field(
        None,
        description='Specific reason for the error. Some of the possible values are:  \n- "groupTooBig" - The group of users requested is too large for a single query. \n- "tooManyCalendarsRequested" - The number of calendars requested is too large for a single query. \n- "notFound" - The requested resource was not found. \n- "internalError" - The API service has encountered an internal error.  Additional error types may be added in the future, so clients should gracefully handle additional error statuses not included in this list.',
    )


class Creator(BaseModel):
    displayName: Optional[str] = Field(
        None, description="The creator's name, if available."
    )
    email: Optional[str] = Field(
        None, description="The creator's email address, if available."
    )
    id: Optional[str] = Field(
        None, description="The creator's Profile ID, if available."
    )
    self: Optional[bool] = Field(
        False,
        description='Whether the creator corresponds to the calendar on which this copy of the event appears. Read-only. The default is False.',
    )


class ExtendedProperties(BaseModel):
    private: Optional[Dict[str, str]] = Field(
        None,
        description='Properties that are private to the copy of the event that appears on this calendar.',
    )
    shared: Optional[Dict[str, str]] = Field(
        None,
        description="Properties that are shared between copies of the event on other attendees' calendars.",
    )


class Gadget(BaseModel):
    display: Optional[str] = Field(
        None,
        description='The gadget\'s display mode. Deprecated. Possible values are:  \n- "icon" - The gadget displays next to the event\'s title in the calendar view. \n- "chip" - The gadget displays when the event is clicked.',
    )
    height: Optional[int] = Field(
        None,
        description="The gadget's height in pixels. The height must be an integer greater than 0. Optional. Deprecated.",
    )
    iconLink: Optional[str] = Field(
        None,
        description="The gadget's icon URL. The URL scheme must be HTTPS. Deprecated.",
    )
    link: Optional[str] = Field(
        None, description="The gadget's URL. The URL scheme must be HTTPS. Deprecated."
    )
    preferences: Optional[Dict[str, str]] = Field(None, description='Preferences.')
    title: Optional[str] = Field(None, description="The gadget's title. Deprecated.")
    type: Optional[str] = Field(None, description="The gadget's type. Deprecated.")
    width: Optional[int] = Field(
        None,
        description="The gadget's width in pixels. The width must be an integer greater than 0. Optional. Deprecated.",
    )


class Organizer(BaseModel):
    displayName: Optional[str] = Field(
        None, description="The organizer's name, if available."
    )
    email: Optional[str] = Field(
        None,
        description="The organizer's email address, if available. It must be a valid email address as per RFC5322.",
    )
    id: Optional[str] = Field(
        None, description="The organizer's Profile ID, if available."
    )
    self: Optional[bool] = Field(
        False,
        description='Whether the organizer corresponds to the calendar on which this copy of the event appears. Read-only. The default is False.',
    )


class Source(BaseModel):
    title: Optional[str] = Field(
        None,
        description='Title of the source; for example a title of a web page or an email subject.',
    )
    url: Optional[str] = Field(
        None,
        description='URL of the source pointing to a resource. The URL scheme must be HTTP or HTTPS.',
    )


class EventAttachment(BaseModel):
    fileId: Optional[str] = Field(
        None,
        description='ID of the attached file. Read-only.\nFor Google Drive files, this is the ID of the corresponding Files resource entry in the Drive API.',
    )
    fileUrl: Optional[str] = Field(
        None,
        description='URL link to the attachment.\nFor adding Google Drive file attachments use the same format as in alternateLink property of the Files resource in the Drive API.\nRequired when adding an attachment.',
    )
    iconLink: Optional[str] = Field(
        None,
        description="URL link to the attachment's icon. This field can only be modified for custom third-party attachments.",
    )
    mimeType: Optional[str] = Field(
        None, description='Internet media type (MIME type) of the attachment.'
    )
    title: Optional[str] = Field(None, description='Attachment title.')


class EventAttendee(BaseModel):
    additionalGuests: Optional[int] = Field(
        0, description='Number of additional guests. Optional. The default is 0.'
    )
    comment: Optional[str] = Field(
        None, description="The attendee's response comment. Optional."
    )
    displayName: Optional[str] = Field(
        None, description="The attendee's name, if available. Optional."
    )
    email: Optional[str] = Field(
        None,
        description="The attendee's email address, if available. This field must be present when adding an attendee. It must be a valid email address as per RFC5322.\nRequired when adding an attendee.",
    )
    id: Optional[str] = Field(
        None, description="The attendee's Profile ID, if available."
    )
    optional: Optional[bool] = Field(
        False,
        description='Whether this is an optional attendee. Optional. The default is False.',
    )
    organizer: Optional[bool] = Field(
        None,
        description='Whether the attendee is the organizer of the event. Read-only. The default is False.',
    )
    resource: Optional[bool] = Field(
        False,
        description='Whether the attendee is a resource. Can only be set when the attendee is added to the event for the first time. Subsequent modifications are ignored. Optional. The default is False.',
    )
    responseStatus: Optional[str] = Field(
        None,
        description='The attendee\'s response status. Possible values are:  \n- "needsAction" - The attendee has not responded to the invitation (recommended for new events). \n- "declined" - The attendee has declined the invitation. \n- "tentative" - The attendee has tentatively accepted the invitation. \n- "accepted" - The attendee has accepted the invitation.  Warning: If you add an event using the values declined, tentative, or accepted, attendees with the "Add invitations to my calendar" setting set to "When I respond to invitation in email" won\'t see an event on their calendar unless they choose to change their invitation response in the event invitation email.',
    )
    self: Optional[bool] = Field(
        False,
        description='Whether this entry represents the calendar on which this copy of the event appears. Read-only. The default is False.',
    )


class EventDateTime(BaseModel):
    date: Optional[date_aliased] = Field(
        None,
        description='The date, in the format "yyyy-mm-dd", if this is an all-day event.',
    )
    dateTime: Optional[datetime] = Field(
        None,
        description='The time, as a combined date-time value (formatted according to RFC3339). A time zone offset is required unless a time zone is explicitly specified in timeZone.',
    )
    timeZone: Optional[str] = Field(
        None,
        description='The time zone in which the time is specified. (Formatted as an IANA Time Zone Database name, e.g. "Europe/Zurich".) For recurring events this field is required and specifies the time zone in which the recurrence is expanded. For single events this field is optional and indicates a custom time zone for the event start/end.',
    )


class EventReminder(BaseModel):
    method: Optional[str] = Field(
        None,
        description='The method used by this reminder. Possible values are:  \n- "email" - Reminders are sent via email. \n- "popup" - Reminders are sent via a UI popup.  \nRequired when adding a reminder.',
    )
    minutes: Optional[int] = Field(
        None,
        description='Number of minutes before the start of the event when the reminder should trigger. Valid values are between 0 and 40320 (4 weeks in minutes).\nRequired when adding a reminder.',
    )


class CustomLocation(BaseModel):
    label: Optional[str] = Field(
        None, description='An optional extra label for additional information.'
    )


class OfficeLocation(BaseModel):
    buildingId: Optional[str] = Field(
        None,
        description="An optional building identifier. This should reference a building ID in the organization's Resources database.",
    )
    deskId: Optional[str] = Field(
        None, description='An optional arbitrary desk identifier.'
    )
    floorId: Optional[str] = Field(
        None, description='An optional arbitrary floor identifier.'
    )
    floorSectionId: Optional[str] = Field(
        None, description='An optional arbitrary floor section identifier.'
    )
    label: Optional[str] = Field(
        None, description='An optional extra label for additional information.'
    )


class EventWorkingLocationProperties(BaseModel):
    customLocation: Optional[CustomLocation] = Field(
        None,
        description='If present, specifies that the user is working from a custom location.',
    )
    homeOffice: Optional[Any] = Field(
        None, description='If present, specifies that the user is working at home.'
    )
    officeLocation: Optional[OfficeLocation] = Field(
        None,
        description='If present, specifies that the user is working from an office.',
    )


class FreeBusyGroup(BaseModel):
    calendars: Optional[List[str]] = Field(
        None, description="List of calendars' identifiers within a group."
    )
    errors: Optional[List[Error]] = Field(
        None, description='Optional error(s) (if computation for the group failed).'
    )


class FreeBusyRequestItem(BaseModel):
    id: Optional[str] = Field(
        None, description='The identifier of a calendar or a group.'
    )


class Setting(BaseModel):
    etag: Optional[str] = Field(None, description='ETag of the resource.')
    id: Optional[str] = Field(None, description='The id of the user setting.')
    kind: Optional[str] = Field(
        'calendar#setting', description='Type of the resource ("calendar#setting").'
    )
    value: Optional[str] = Field(
        None,
        description='Value of the user setting. The format of the value depends on the ID of the setting. It must always be a UTF-8 string of length up to 1024 characters.',
    )


class Settings(BaseModel):
    etag: Optional[str] = Field(None, description='Etag of the collection.')
    items: Optional[List[Setting]] = Field(None, description='List of user settings.')
    kind: Optional[str] = Field(
        'calendar#settings', description='Type of the collection ("calendar#settings").'
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='Token used to access the next page of this result. Omitted if no further results are available, in which case nextSyncToken is provided.',
    )
    nextSyncToken: Optional[str] = Field(
        None,
        description='Token used at a later point in time to retrieve only the entries that have changed since this result was returned. Omitted if further results are available, in which case nextPageToken is provided.',
    )


class TimePeriod(BaseModel):
    end: Optional[datetime] = Field(
        None, description='The (exclusive) end of the time period.'
    )
    start: Optional[datetime] = Field(
        None, description='The (inclusive) start of the time period.'
    )


class Alt(Enum):
    json = 'json'


class OrderBy(Enum):
    startTime = 'startTime'
    updated = 'updated'


class EventTypes(RootModel[List[str]]):
    root: List[str]


class PrivateExtendedProperty(RootModel[List[str]]):
    root: List[str]


class SharedExtendedProperty(RootModel[List[str]]):
    root: List[str]


class SendUpdates(Enum):
    all = 'all'
    externalOnly = 'externalOnly'
    none = 'none'


class MinAccessRole(Enum):
    freeBusyReader = 'freeBusyReader'
    owner = 'owner'
    reader = 'reader'
    writer = 'writer'


class Acl(BaseModel):
    etag: Optional[str] = Field(None, description='ETag of the collection.')
    items: Optional[List[AclRule]] = Field(
        None, description='List of rules on the access control list.'
    )
    kind: Optional[str] = Field(
        'calendar#acl', description='Type of the collection ("calendar#acl").'
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='Token used to access the next page of this result. Omitted if no further results are available, in which case nextSyncToken is provided.',
    )
    nextSyncToken: Optional[str] = Field(
        None,
        description='Token used at a later point in time to retrieve only the entries that have changed since this result was returned. Omitted if further results are available, in which case nextPageToken is provided.',
    )


class Calendar(BaseModel):
    conferenceProperties: Optional[ConferenceProperties] = Field(
        None,
        description='Conferencing properties for this calendar, for example what types of conferences are allowed.',
    )
    description: Optional[str] = Field(
        None, description='Description of the calendar. Optional.'
    )
    etag: Optional[str] = Field(None, description='ETag of the resource.')
    id: Optional[str] = Field(
        None,
        description='Identifier of the calendar. To retrieve IDs call the calendarList.list() method.',
    )
    kind: Optional[str] = Field(
        'calendar#calendar', description='Type of the resource ("calendar#calendar").'
    )
    location: Optional[str] = Field(
        None,
        description='Geographic location of the calendar as free-form text. Optional.',
    )
    summary: Optional[str] = Field(None, description='Title of the calendar.')
    timeZone: Optional[str] = Field(
        None,
        description='The time zone of the calendar. (Formatted as an IANA Time Zone Database name, e.g. "Europe/Zurich".) Optional.',
    )


class NotificationSettings(BaseModel):
    notifications: Optional[List[CalendarNotification]] = Field(
        None, description='The list of notifications set for this calendar.'
    )


class CalendarListEntry(BaseModel):
    accessRole: Optional[str] = Field(
        None,
        description='The effective access role that the authenticated user has on the calendar. Read-only. Possible values are:  \n- "freeBusyReader" - Provides read access to free/busy information. \n- "reader" - Provides read access to the calendar. Private events will appear to users with reader access, but event details will be hidden. \n- "writer" - Provides read and write access to the calendar. Private events will appear to users with writer access, and event details will be visible. \n- "owner" - Provides ownership of the calendar. This role has all of the permissions of the writer role with the additional ability to see and manipulate ACLs.',
    )
    backgroundColor: Optional[str] = Field(
        None,
        description='The main color of the calendar in the hexadecimal format "#0088aa". This property supersedes the index-based colorId property. To set or change this property, you need to specify colorRgbFormat=true in the parameters of the insert, update and patch methods. Optional.',
    )
    colorId: Optional[str] = Field(
        None,
        description='The color of the calendar. This is an ID referring to an entry in the calendar section of the colors definition (see the colors endpoint). This property is superseded by the backgroundColor and foregroundColor properties and can be ignored when using these properties. Optional.',
    )
    conferenceProperties: Optional[ConferenceProperties] = Field(
        None,
        description='Conferencing properties for this calendar, for example what types of conferences are allowed.',
    )
    defaultReminders: Optional[List[EventReminder]] = Field(
        None,
        description='The default reminders that the authenticated user has for this calendar.',
    )
    deleted: Optional[bool] = Field(
        False,
        description='Whether this calendar list entry has been deleted from the calendar list. Read-only. Optional. The default is False.',
    )
    description: Optional[str] = Field(
        None, description='Description of the calendar. Optional. Read-only.'
    )
    etag: Optional[str] = Field(None, description='ETag of the resource.')
    foregroundColor: Optional[str] = Field(
        None,
        description='The foreground color of the calendar in the hexadecimal format "#ffffff". This property supersedes the index-based colorId property. To set or change this property, you need to specify colorRgbFormat=true in the parameters of the insert, update and patch methods. Optional.',
    )
    hidden: Optional[bool] = Field(
        False,
        description='Whether the calendar has been hidden from the list. Optional. The attribute is only returned when the calendar is hidden, in which case the value is true.',
    )
    id: Optional[str] = Field(None, description='Identifier of the calendar.')
    kind: Optional[str] = Field(
        'calendar#calendarListEntry',
        description='Type of the resource ("calendar#calendarListEntry").',
    )
    location: Optional[str] = Field(
        None,
        description='Geographic location of the calendar as free-form text. Optional. Read-only.',
    )
    notificationSettings: Optional[NotificationSettings] = Field(
        None,
        description='The notifications that the authenticated user is receiving for this calendar.',
    )
    primary: Optional[bool] = Field(
        False,
        description='Whether the calendar is the primary calendar of the authenticated user. Read-only. Optional. The default is False.',
    )
    selected: Optional[bool] = Field(
        False,
        description='Whether the calendar content shows up in the calendar UI. Optional. The default is False.',
    )
    summary: Optional[str] = Field(
        None, description='Title of the calendar. Read-only.'
    )
    summaryOverride: Optional[str] = Field(
        None,
        description='The summary that the authenticated user has set for this calendar. Optional.',
    )
    timeZone: Optional[str] = Field(
        None, description='The time zone of the calendar. Optional. Read-only.'
    )


class ConferenceParameters(BaseModel):
    addOnParameters: Optional[ConferenceParametersAddOnParameters] = Field(
        None, description='Additional add-on specific data.'
    )


class ConferenceSolution(BaseModel):
    iconUri: Optional[str] = Field(
        None, description='The user-visible icon for this solution.'
    )
    key: Optional[ConferenceSolutionKey] = Field(
        None,
        description='The key which can uniquely identify the conference solution for this event.',
    )
    name: Optional[str] = Field(
        None, description='The user-visible name of this solution. Not localized.'
    )


class Reminders(BaseModel):
    overrides: Optional[List[EventReminder]] = Field(
        None,
        description="If the event doesn't use the default reminders, this lists the reminders specific to the event, or, if not set, indicates that no reminders are set for this event. The maximum number of override reminders is 5.",
    )
    useDefault: Optional[bool] = Field(
        None,
        description='Whether the default reminders of the calendar apply to the event.',
    )


class FreeBusyCalendar(BaseModel):
    busy: Optional[List[TimePeriod]] = Field(
        None,
        description='List of time ranges during which this calendar should be regarded as busy.',
    )
    errors: Optional[List[Error]] = Field(
        None, description='Optional error(s) (if computation for the calendar failed).'
    )


class FreeBusyRequest(BaseModel):
    calendarExpansionMax: Optional[int] = Field(
        None,
        description='Maximal number of calendars for which FreeBusy information is to be provided. Optional. Maximum value is 50.',
    )
    groupExpansionMax: Optional[int] = Field(
        None,
        description='Maximal number of calendar identifiers to be provided for a single group. Optional. An error is returned for a group with more members than this value. Maximum value is 100.',
    )
    items: Optional[List[FreeBusyRequestItem]] = Field(
        None, description='List of calendars and/or groups to query.'
    )
    timeMax: Optional[datetime] = Field(
        None,
        description='The end of the interval for the query formatted as per RFC3339.',
    )
    timeMin: Optional[datetime] = Field(
        None,
        description='The start of the interval for the query formatted as per RFC3339.',
    )
    timeZone: Optional[str] = Field(
        'UTC',
        description='Time zone used in the response. Optional. The default is UTC.',
    )


class FreeBusyResponse(BaseModel):
    calendars: Optional[Dict[str, FreeBusyCalendar]] = Field(
        None, description='List of free/busy information for calendars.'
    )
    groups: Optional[Dict[str, FreeBusyGroup]] = Field(
        None, description='Expansion of groups.'
    )
    kind: Optional[str] = Field(
        'calendar#freeBusy', description='Type of the resource ("calendar#freeBusy").'
    )
    timeMax: Optional[datetime] = Field(None, description='The end of the interval.')
    timeMin: Optional[datetime] = Field(None, description='The start of the interval.')


class CalendarList(BaseModel):
    etag: Optional[str] = Field(None, description='ETag of the collection.')
    items: Optional[List[CalendarListEntry]] = Field(
        None, description="Calendars that are present on the user's calendar list."
    )
    kind: Optional[str] = Field(
        'calendar#calendarList',
        description='Type of the collection ("calendar#calendarList").',
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='Token used to access the next page of this result. Omitted if no further results are available, in which case nextSyncToken is provided.',
    )
    nextSyncToken: Optional[str] = Field(
        None,
        description='Token used at a later point in time to retrieve only the entries that have changed since this result was returned. Omitted if further results are available, in which case nextPageToken is provided.',
    )


class ConferenceData(BaseModel):
    conferenceId: Optional[str] = Field(
        None,
        description='The ID of the conference.\nCan be used by developers to keep track of conferences, should not be displayed to users.\nThe ID value is formed differently for each conference solution type:  \n- eventHangout: ID is not set. (This conference type is deprecated.)\n- eventNamedHangout: ID is the name of the Hangout. (This conference type is deprecated.)\n- hangoutsMeet: ID is the 10-letter meeting code, for example aaa-bbbb-ccc.\n- addOn: ID is defined by the third-party provider.  Optional.',
    )
    conferenceSolution: Optional[ConferenceSolution] = Field(
        None,
        description='The conference solution, such as Google Meet.\nUnset for a conference with a failed create request.\nEither conferenceSolution and at least one entryPoint, or createRequest is required.',
    )
    createRequest: Optional[CreateConferenceRequest] = Field(
        None,
        description='A request to generate a new conference and attach it to the event. The data is generated asynchronously. To see whether the data is present check the status field.\nEither conferenceSolution and at least one entryPoint, or createRequest is required.',
    )
    entryPoints: Optional[List[EntryPoint]] = Field(
        None,
        description='Information about individual conference entry points, such as URLs or phone numbers.\nAll of them must belong to the same conference.\nEither conferenceSolution and at least one entryPoint, or createRequest is required.',
    )
    notes: Optional[str] = Field(
        None,
        description='Additional notes (such as instructions from the domain administrator, legal notices) to display to the user. Can contain HTML. The maximum length is 2048 characters. Optional.',
    )
    parameters: Optional[ConferenceParameters] = Field(
        None,
        description='Additional properties related to a conference. An example would be a solution-specific setting for enabling video streaming.',
    )
    signature: Optional[str] = Field(
        None,
        description='The signature of the conference data.\nGenerated on server side.\nUnset for a conference with a failed create request.\nOptional for a conference with a pending create request.',
    )


class Event(BaseModel):
    anyoneCanAddSelf: Optional[bool] = Field(
        False,
        description='Whether anyone can invite themselves to the event (deprecated). Optional. The default is False.',
    )
    attachments: Optional[List[EventAttachment]] = Field(
        None,
        description='File attachments for the event.\nIn order to modify attachments the supportsAttachments request parameter should be set to true.\nThere can be at most 25 attachments per event,',
    )
    attendees: Optional[List[EventAttendee]] = Field(
        None,
        description='The attendees of the event. See the Events with attendees guide for more information on scheduling events with other calendar users. Service accounts need to use domain-wide delegation of authority to populate the attendee list.',
    )
    attendeesOmitted: Optional[bool] = Field(
        False,
        description="Whether attendees may have been omitted from the event's representation. When retrieving an event, this may be due to a restriction specified by the maxAttendee query parameter. When updating an event, this can be used to only update the participant's response. Optional. The default is False.",
    )
    colorId: Optional[str] = Field(
        None,
        description='The color of the event. This is an ID referring to an entry in the event section of the colors definition (see the  colors endpoint). Optional.',
    )
    conferenceData: Optional[ConferenceData] = Field(
        None,
        description='The conference-related information, such as details of a Google Meet conference. To create new conference details use the createRequest field. To persist your changes, remember to set the conferenceDataVersion request parameter to 1 for all event modification requests.',
    )
    created: Optional[datetime] = Field(
        None,
        description='Creation time of the event (as a RFC3339 timestamp). Read-only.',
    )
    creator: Optional[Creator] = Field(
        None, description='The creator of the event. Read-only.'
    )
    description: Optional[str] = Field(
        None, description='Description of the event. Can contain HTML. Optional.'
    )
    end: Optional[EventDateTime] = Field(
        None,
        description='The (exclusive) end time of the event. For a recurring event, this is the end time of the first instance.',
    )
    endTimeUnspecified: Optional[bool] = Field(
        False,
        description='Whether the end time is actually unspecified. An end time is still provided for compatibility reasons, even if this attribute is set to True. The default is False.',
    )
    etag: Optional[str] = Field(None, description='ETag of the resource.')
    eventType: Optional[str] = Field(
        'default',
        description='Specific type of the event. Read-only. Possible values are:  \n- "default" - A regular event or not further specified. \n- "outOfOffice" - An out-of-office event. \n- "focusTime" - A focus-time event. \n- "workingLocation" - A working location event. Developer Preview.',
    )
    extendedProperties: Optional[ExtendedProperties] = Field(
        None, description='Extended properties of the event.'
    )
    gadget: Optional[Gadget] = Field(
        None,
        description='A gadget that extends this event. Gadgets are deprecated; this structure is instead only used for returning birthday calendar metadata.',
    )
    guestsCanInviteOthers: Optional[bool] = Field(
        True,
        description='Whether attendees other than the organizer can invite others to the event. Optional. The default is True.',
    )
    guestsCanModify: Optional[bool] = Field(
        False,
        description='Whether attendees other than the organizer can modify the event. Optional. The default is False.',
    )
    guestsCanSeeOtherGuests: Optional[bool] = Field(
        True,
        description="Whether attendees other than the organizer can see who the event's attendees are. Optional. The default is True.",
    )
    hangoutLink: Optional[str] = Field(
        None,
        description='An absolute link to the Google Hangout associated with this event. Read-only.',
    )
    htmlLink: Optional[str] = Field(
        None,
        description='An absolute link to this event in the Google Calendar Web UI. Read-only.',
    )
    iCalUID: Optional[str] = Field(
        None,
        description='Event unique identifier as defined in RFC5545. It is used to uniquely identify events accross calendaring systems and must be supplied when importing events via the import method.\nNote that the iCalUID and the id are not identical and only one of them should be supplied at event creation time. One difference in their semantics is that in recurring events, all occurrences of one event have different ids while they all share the same iCalUIDs. To retrieve an event using its iCalUID, call the events.list method using the iCalUID parameter. To retrieve an event using its id, call the events.get method.',
    )
    id: Optional[str] = Field(
        None,
        description='Opaque identifier of the event. When creating new single or recurring events, you can specify their IDs. Provided IDs must follow these rules:  \n- characters allowed in the ID are those used in base32hex encoding, i.e. lowercase letters a-v and digits 0-9, see section 3.1.2 in RFC2938 \n- the length of the ID must be between 5 and 1024 characters \n- the ID must be unique per calendar  Due to the globally distributed nature of the system, we cannot guarantee that ID collisions will be detected at event creation time. To minimize the risk of collisions we recommend using an established UUID algorithm such as one described in RFC4122.\nIf you do not specify an ID, it will be automatically generated by the server.\nNote that the icalUID and the id are not identical and only one of them should be supplied at event creation time. One difference in their semantics is that in recurring events, all occurrences of one event have different ids while they all share the same icalUIDs.',
    )
    kind: Optional[str] = Field(
        'calendar#event', description='Type of the resource ("calendar#event").'
    )
    location: Optional[str] = Field(
        None,
        description='Geographic location of the event as free-form text. Optional.',
    )
    locked: Optional[bool] = Field(
        False,
        description='Whether this is a locked event copy where no changes can be made to the main event fields "summary", "description", "location", "start", "end" or "recurrence". The default is False. Read-Only.',
    )
    organizer: Optional[Organizer] = Field(
        None,
        description='The organizer of the event. If the organizer is also an attendee, this is indicated with a separate entry in attendees with the organizer field set to True. To change the organizer, use the move operation. Read-only, except when importing an event.',
    )
    originalStartTime: Optional[EventDateTime] = Field(
        None,
        description='For an instance of a recurring event, this is the time at which this event would start according to the recurrence data in the recurring event identified by recurringEventId. It uniquely identifies the instance within the recurring event series even if the instance was moved to a different time. Immutable.',
    )
    privateCopy: Optional[bool] = Field(
        False,
        description='If set to True, Event propagation is disabled. Note that it is not the same thing as Private event properties. Optional. Immutable. The default is False.',
    )
    recurrence: Optional[List[str]] = Field(
        None,
        description='List of RRULE, EXRULE, RDATE and EXDATE lines for a recurring event, as specified in RFC5545. Note that DTSTART and DTEND lines are not allowed in this field; event start and end times are specified in the start and end fields. This field is omitted for single events or instances of recurring events.',
    )
    recurringEventId: Optional[str] = Field(
        None,
        description='For an instance of a recurring event, this is the id of the recurring event to which this instance belongs. Immutable.',
    )
    reminders: Optional[Reminders] = Field(
        None,
        description="Information about the event's reminders for the authenticated user.",
    )
    sequence: Optional[int] = Field(
        None, description='Sequence number as per iCalendar.'
    )
    source: Optional[Source] = Field(
        None,
        description='Source from which the event was created. For example, a web page, an email message or any document identifiable by an URL with HTTP or HTTPS scheme. Can only be seen or modified by the creator of the event.',
    )
    start: Optional[EventDateTime] = Field(
        None,
        description='The (inclusive) start time of the event. For a recurring event, this is the start time of the first instance.',
    )
    status: Optional[str] = Field(
        None,
        description='Status of the event. Optional. Possible values are:  \n- "confirmed" - The event is confirmed. This is the default status. \n- "tentative" - The event is tentatively confirmed. \n- "cancelled" - The event is cancelled (deleted). The list method returns cancelled events only on incremental sync (when syncToken or updatedMin are specified) or if the showDeleted flag is set to true. The get method always returns them.\nA cancelled status represents two different states depending on the event type:  \n- Cancelled exceptions of an uncancelled recurring event indicate that this instance should no longer be presented to the user. Clients should store these events for the lifetime of the parent recurring event.\nCancelled exceptions are only guaranteed to have values for the id, recurringEventId and originalStartTime fields populated. The other fields might be empty.  \n- All other cancelled events represent deleted events. Clients should remove their locally synced copies. Such cancelled events will eventually disappear, so do not rely on them being available indefinitely.\nDeleted events are only guaranteed to have the id field populated.   On the organizer\'s calendar, cancelled events continue to expose event details (summary, location, etc.) so that they can be restored (undeleted). Similarly, the events to which the user was invited and that they manually removed continue to provide details. However, incremental sync requests with showDeleted set to false will not return these details.\nIf an event changes its organizer (for example via the move operation) and the original organizer is not on the attendee list, it will leave behind a cancelled event where only the id field is guaranteed to be populated.',
    )
    summary: Optional[str] = Field(None, description='Title of the event.')
    transparency: Optional[str] = Field(
        'opaque',
        description='Whether the event blocks time on the calendar. Optional. Possible values are:  \n- "opaque" - Default value. The event does block time on the calendar. This is equivalent to setting Show me as to Busy in the Calendar UI. \n- "transparent" - The event does not block time on the calendar. This is equivalent to setting Show me as to Available in the Calendar UI.',
    )
    updated: Optional[datetime] = Field(
        None,
        description='Last modification time of the event (as a RFC3339 timestamp). Read-only.',
    )
    visibility: Optional[str] = Field(
        'default',
        description='Visibility of the event. Optional. Possible values are:  \n- "default" - Uses the default visibility for events on the calendar. This is the default value. \n- "public" - The event is public and event details are visible to all readers of the calendar. \n- "private" - The event is private and only event attendees may view event details. \n- "confidential" - The event is private. This value is provided for compatibility reasons.',
    )
    workingLocationProperties: Optional[EventWorkingLocationProperties] = Field(
        None, description='Developer Preview: Working Location event data. Read-only.'
    )


class Events(BaseModel):
    accessRole: Optional[str] = Field(
        None,
        description='The user\'s access role for this calendar. Read-only. Possible values are:  \n- "none" - The user has no access. \n- "freeBusyReader" - The user has read access to free/busy information. \n- "reader" - The user has read access to the calendar. Private events will appear to users with reader access, but event details will be hidden. \n- "writer" - The user has read and write access to the calendar. Private events will appear to users with writer access, and event details will be visible. \n- "owner" - The user has ownership of the calendar. This role has all of the permissions of the writer role with the additional ability to see and manipulate ACLs.',
    )
    defaultReminders: Optional[List[EventReminder]] = Field(
        None,
        description='The default reminders on the calendar for the authenticated user. These reminders apply to all events on this calendar that do not explicitly override them (i.e. do not have reminders.useDefault set to True).',
    )
    description: Optional[str] = Field(
        None, description='Description of the calendar. Read-only.'
    )
    etag: Optional[str] = Field(None, description='ETag of the collection.')
    items: Optional[List[Event]] = Field(
        None, description='List of events on the calendar.'
    )
    kind: Optional[str] = Field(
        'calendar#events', description='Type of the collection ("calendar#events").'
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='Token used to access the next page of this result. Omitted if no further results are available, in which case nextSyncToken is provided.',
    )
    nextSyncToken: Optional[str] = Field(
        None,
        description='Token used at a later point in time to retrieve only the entries that have changed since this result was returned. Omitted if further results are available, in which case nextPageToken is provided.',
    )
    summary: Optional[str] = Field(
        None, description='Title of the calendar. Read-only.'
    )
    timeZone: Optional[str] = Field(
        None, description='The time zone of the calendar. Read-only.'
    )
    updated: Optional[datetime] = Field(
        None,
        description='Last modification time of the calendar (as a RFC3339 timestamp). Read-only.',
    )
